[2023-06-11T02:07:53.883+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: fhv_taxi_data.download_dataset_task scheduled__2022-06-02T07:00:00+00:00 [queued]>
[2023-06-11T02:07:53.888+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: fhv_taxi_data.download_dataset_task scheduled__2022-06-02T07:00:00+00:00 [queued]>
[2023-06-11T02:07:53.888+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-06-11T02:07:53.889+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 2
[2023-06-11T02:07:53.889+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-06-11T02:07:53.897+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): download_dataset_task> on 2022-06-02 07:00:00+00:00
[2023-06-11T02:07:53.901+0000] {standard_task_runner.py:54} INFO - Started process 9057 to run task
[2023-06-11T02:07:53.904+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'fhv_taxi_data', 'download_dataset_task', 'scheduled__2022-06-02T07:00:00+00:00', '--job-id', '826', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_multiFile_v02.py', '--cfg-path', '/tmp/tmp8mqib0lm']
[2023-06-11T02:07:53.905+0000] {standard_task_runner.py:83} INFO - Job 826: Subtask download_dataset_task
[2023-06-11T02:07:53.906+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/data_ingestion_gcs_multiFile_v02.py
[2023-06-11T02:07:53.962+0000] {data_ingestion_gcs_multiFile_v02.py:20} INFO - dtc_data_lake_dtc-dezc-001 is the bucket.
[2023-06-11T02:07:53.977+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:545: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2023-06-11T02:07:54.015+0000] {task_command.py:384} INFO - Running <TaskInstance: fhv_taxi_data.download_dataset_task scheduled__2022-06-02T07:00:00+00:00 [running]> on host f41d61956f54
[2023-06-11T02:07:54.036+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:204: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-06-11T02:07:54.060+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=fhv_taxi_data
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2022-06-02T07:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-02T07:00:00+00:00
[2023-06-11T02:07:54.061+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-11T02:07:54.062+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'curl -sSLf https://github.com/DataTalksClub/nyc-tlc-data/releases/download/fhv/fhv_tripdata_2022-06.csv.gz > /opt/***/fhv_tripdata_2022-06.csv.gz']
[2023-06-11T02:07:54.071+0000] {subprocess.py:86} INFO - Output:
[2023-06-11T02:07:54.325+0000] {subprocess.py:93} INFO - curl: (22) The requested URL returned error: 404
[2023-06-11T02:07:54.331+0000] {subprocess.py:97} INFO - Command exited with return code 22
[2023-06-11T02:07:54.344+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 22.
[2023-06-11T02:07:54.349+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=fhv_taxi_data, task_id=download_dataset_task, execution_date=20220602T070000, start_date=20230611T020753, end_date=20230611T020754
[2023-06-11T02:07:54.360+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 826 for task download_dataset_task (Bash command failed. The command returned a non-zero exit code 22.; 9057)
[2023-06-11T02:07:54.406+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-06-11T02:07:54.427+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
