[2023-06-10T01:12:20.645+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: taxi_zone_data.format_to_parquet_task scheduled__2023-06-09T00:00:00+00:00 [queued]>
[2023-06-10T01:12:20.650+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: taxi_zone_data.format_to_parquet_task scheduled__2023-06-09T00:00:00+00:00 [queued]>
[2023-06-10T01:12:20.651+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-06-10T01:12:20.651+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2023-06-10T01:12:20.652+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-06-10T01:12:20.658+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): format_to_parquet_task> on 2023-06-09 00:00:00+00:00
[2023-06-10T01:12:20.662+0000] {standard_task_runner.py:54} INFO - Started process 763 to run task
[2023-06-10T01:12:20.665+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'taxi_zone_data', 'format_to_parquet_task', 'scheduled__2023-06-09T00:00:00+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_multiFile_v02.py', '--cfg-path', '/tmp/tmpih6i_awr']
[2023-06-10T01:12:20.666+0000] {standard_task_runner.py:83} INFO - Job 21: Subtask format_to_parquet_task
[2023-06-10T01:12:20.667+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/data_ingestion_gcs_multiFile_v02.py
[2023-06-10T01:12:20.721+0000] {data_ingestion_gcs_multiFile_v02.py:20} INFO - dtc_data_lake_dtc-dezc-001 is the bucket.
[2023-06-10T01:12:20.736+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:545: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2023-06-10T01:12:20.770+0000] {task_command.py:384} INFO - Running <TaskInstance: taxi_zone_data.format_to_parquet_task scheduled__2023-06-09T00:00:00+00:00 [running]> on host f41d61956f54
[2023-06-10T01:12:20.813+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=taxi_zone_data
AIRFLOW_CTX_TASK_ID=format_to_parquet_task
AIRFLOW_CTX_EXECUTION_DATE=2023-06-09T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-09T00:00:00+00:00
[2023-06-10T01:12:20.890+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion_gcs_multiFile_v02.py", line 33, in format_to_parquet
    table = pv.read_csv(src_file)
  File "pyarrow/_csv.pyx", line 886, in pyarrow._csv.read_csv
  File "pyarrow/_csv.pyx", line 895, in pyarrow._csv.read_csv
  File "pyarrow/error.pxi", line 143, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 99, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: CSV parse error: Expected 1 columns, got 4:     <meta name="enabled-features" content="TURBO_EXPERIMENT_RISKY,IMAGE_METRIC_TRACKING,GEOJSON_ ...
[2023-06-10T01:12:20.899+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=taxi_zone_data, task_id=format_to_parquet_task, execution_date=20230609T000000, start_date=20230610T011220, end_date=20230610T011220
[2023-06-10T01:12:20.907+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 21 for task format_to_parquet_task (CSV parse error: Expected 1 columns, got 4:     <meta name="enabled-features" content="TURBO_EXPERIMENT_RISKY,IMAGE_METRIC_TRACKING,GEOJSON_ ...; 763)
[2023-06-10T01:12:20.923+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-06-10T01:12:20.963+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
