[2023-06-06T19:26:24.488+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2023-06-05T00:00:00+00:00 [queued]>
[2023-06-06T19:26:24.493+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2023-06-05T00:00:00+00:00 [queued]>
[2023-06-06T19:26:24.494+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-06-06T19:26:24.494+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2023-06-06T19:26:24.495+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-06-06T19:26:24.502+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2023-06-05 00:00:00+00:00
[2023-06-06T19:26:24.506+0000] {standard_task_runner.py:54} INFO - Started process 184 to run task
[2023-06-06T19:26:24.510+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'local_to_gcs_task', 'scheduled__2023-06-05T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs.py', '--cfg-path', '/tmp/tmphkxh489r']
[2023-06-06T19:26:24.512+0000] {standard_task_runner.py:83} INFO - Job 5: Subtask local_to_gcs_task
[2023-06-06T19:26:24.513+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/data_ingestion_gcs.py
[2023-06-06T19:26:24.526+0000] {data_ingestion_gcs.py:24} INFO - Dataset file is yellow_tripdata_2021-01.csv.gz, url is https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2021-01.csv.gz, local_home is /opt/***, parquet file is yellow_tripdata_2021-01.parquet
[2023-06-06T19:26:24.527+0000] {data_ingestion_gcs.py:31} INFO - dtc_data_lake_dtc-dezc-001 is the bucket, dtc-dezc-001 is the project id, trips_data_all is the bigquery dataset.
[2023-06-06T19:26:24.540+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:545: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2023-06-06T19:26:24.579+0000] {task_command.py:384} INFO - Running <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2023-06-05T00:00:00+00:00 [running]> on host 5b07d5f4e84f
[2023-06-06T19:26:24.622+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2023-06-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-05T00:00:00+00:00
[2023-06-06T19:26:24.629+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/google/auth/_default.py:81: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. We recommend you rerun `gcloud auth application-default login` and make sure a quota project is added. Or you can use service accounts instead. For more information about service accounts, see https://cloud.google.com/docs/authentication/
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)

[2023-06-06T19:26:24.630+0000] {_default.py:612} WARNING - No project ID could be determined. Consider running `gcloud config set project` or setting the GOOGLE_CLOUD_PROJECT environment variable
[2023-06-06T19:26:24.630+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion_gcs.py", line 67, in upload_to_gcs
    client = storage.Client()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/client.py", line 128, in __init__
    _http=_http,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 320, in __init__
    _ClientProjectMixin.__init__(self, project=project, credentials=credentials)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 272, in __init__
    "Project was not passed and could not be "
OSError: Project was not passed and could not be determined from the environment.
[2023-06-06T19:26:24.638+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_gcs_dag, task_id=local_to_gcs_task, execution_date=20230605T000000, start_date=20230606T192624, end_date=20230606T192624
[2023-06-06T19:26:24.645+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 5 for task local_to_gcs_task (Project was not passed and could not be determined from the environment.; 184)
[2023-06-06T19:26:24.682+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-06-06T19:26:24.702+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-06-06T20:10:21.068+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2023-06-05T00:00:00+00:00 [queued]>
[2023-06-06T20:10:21.076+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2023-06-05T00:00:00+00:00 [queued]>
[2023-06-06T20:10:21.077+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-06-06T20:10:21.078+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2023-06-06T20:10:21.078+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-06-06T20:10:21.089+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2023-06-05 00:00:00+00:00
[2023-06-06T20:10:21.095+0000] {standard_task_runner.py:54} INFO - Started process 182 to run task
[2023-06-06T20:10:21.100+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'local_to_gcs_task', 'scheduled__2023-06-05T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs.py', '--cfg-path', '/tmp/tmpzqfalekh']
[2023-06-06T20:10:21.103+0000] {standard_task_runner.py:83} INFO - Job 5: Subtask local_to_gcs_task
[2023-06-06T20:10:21.104+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/data_ingestion_gcs.py
[2023-06-06T20:10:21.120+0000] {data_ingestion_gcs.py:24} INFO - Dataset file is yellow_tripdata_2021-01.csv.gz, url is https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2021-01.csv.gz, local_home is /opt/***, parquet file is yellow_tripdata_2021-01.parquet
[2023-06-06T20:10:21.120+0000] {data_ingestion_gcs.py:32} INFO - dtc_data_lake_dtc-dezc-001 is the bucket,  dtc-dezc is the project name, dtc-dezc-001 is the project id, trips_data_all is the bigquery dataset.
[2023-06-06T20:10:21.136+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:545: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2023-06-06T20:10:21.179+0000] {task_command.py:384} INFO - Running <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2023-06-05T00:00:00+00:00 [running]> on host 1d8c795fd30d
[2023-06-06T20:10:21.226+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2023-06-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-05T00:00:00+00:00
[2023-06-06T20:10:21.233+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/google/auth/_default.py:81: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. We recommend you rerun `gcloud auth application-default login` and make sure a quota project is added. Or you can use service accounts instead. For more information about service accounts, see https://cloud.google.com/docs/authentication/
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)

[2023-06-06T20:10:22.527+0000] {data_ingestion_gcs.py:73} INFO - Blob is <Blob: dtc_data_lake_dtc-dezc-001, raw/yellow_tripdata_2021-01.parquet, None>
[2023-06-06T20:10:42.566+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-06-06T20:10:42.589+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=local_to_gcs_task, execution_date=20230605T000000, start_date=20230606T201021, end_date=20230606T201042
[2023-06-06T20:10:42.636+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-06-06T20:10:42.658+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
