[2023-06-11T01:57:44.332+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: fhv_taxi_data.download_dataset_task scheduled__2022-01-02T07:00:00+00:00 [queued]>
[2023-06-11T01:57:44.338+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: fhv_taxi_data.download_dataset_task scheduled__2022-01-02T07:00:00+00:00 [queued]>
[2023-06-11T01:57:44.338+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-06-11T01:57:44.339+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 2
[2023-06-11T01:57:44.339+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-06-11T01:57:44.346+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): download_dataset_task> on 2022-01-02 07:00:00+00:00
[2023-06-11T01:57:44.350+0000] {standard_task_runner.py:54} INFO - Started process 8441 to run task
[2023-06-11T01:57:44.354+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'fhv_taxi_data', 'download_dataset_task', 'scheduled__2022-01-02T07:00:00+00:00', '--job-id', '809', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_multiFile_v02.py', '--cfg-path', '/tmp/tmpxvhgu5sm']
[2023-06-11T01:57:44.355+0000] {standard_task_runner.py:83} INFO - Job 809: Subtask download_dataset_task
[2023-06-11T01:57:44.356+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/data_ingestion_gcs_multiFile_v02.py
[2023-06-11T01:57:44.413+0000] {data_ingestion_gcs_multiFile_v02.py:20} INFO - dtc_data_lake_dtc-dezc-001 is the bucket.
[2023-06-11T01:57:44.428+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:545: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2023-06-11T01:57:44.469+0000] {task_command.py:384} INFO - Running <TaskInstance: fhv_taxi_data.download_dataset_task scheduled__2022-01-02T07:00:00+00:00 [running]> on host f41d61956f54
[2023-06-11T01:57:44.494+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:204: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-06-11T01:57:44.518+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=fhv_taxi_data
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2022-01-02T07:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-02T07:00:00+00:00
[2023-06-11T01:57:44.520+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-11T01:57:44.521+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'curl -sSLf https://github.com/DataTalksClub/nyc-tlc-data/releases/download/fhv/fhv_tripdata_2022-01.csv.gz > /opt/***/fhv_tripdata_2022-01.csv.gz']
[2023-06-11T01:57:44.530+0000] {subprocess.py:86} INFO - Output:
[2023-06-11T01:57:44.821+0000] {subprocess.py:93} INFO - curl: (22) The requested URL returned error: 404
[2023-06-11T01:57:44.835+0000] {subprocess.py:97} INFO - Command exited with return code 22
[2023-06-11T01:57:44.868+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 22.
[2023-06-11T01:57:44.874+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=fhv_taxi_data, task_id=download_dataset_task, execution_date=20220102T070000, start_date=20230611T015744, end_date=20230611T015744
[2023-06-11T01:57:44.891+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 809 for task download_dataset_task (Bash command failed. The command returned a non-zero exit code 22.; 8441)
[2023-06-11T01:57:44.946+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-06-11T01:57:44.970+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
